#!/bin/bash

currentFilepath=${BASH_SOURCE[0]}
currentDirpath=$(dirname "${currentFilepath}")

echo "currentFilepath = $currentFilepath"
echo "currentDirpath = $currentDirpath"

# yamlFilepath="$currentDirpath/support/lib/bash-yaml/yaml.sh"
# echo "yamlFilepath = $yamlFilepath"

# source "$yamlFilepath"

projectDirpath=$(pwd)
echo "projectFilepath = $projectFilepath"

configFilepath="$projectDirpath/.tmux-config.json"
echo "configFilepath = $configFilepath"

status_bg=$(cat $configFilepath | jq --raw-output '.status_bg') # raw-output => no quotes
status_fg=$(cat $configFilepath | jq --raw-output '.status_fg')
# create_variables "$configFilepath"

echo "status_bg = $status_bg"
echo "status_fg = $status_fg"

function PWD {
  pwd | awk -F\/ '{print $(NF)}'
}

session_name=$1

if [ -z $1 ]
then
  session_name=$(cat $configFilepath | jq --raw-output '.session_name')
fi

if [ -z $session_name ]
then
  session_name="$(PWD)"
fi

count=$( tmux ls | grep "^$session_name:" | wc -c )

if [ "$(( $count + 1 ))" != "1" ];
then
  echo "session already exists"

else
  tmux new-session -d -s $session_name

  tmux new-window -t $session_name
  tmux new-window -t $session_name

  tmux select-window -t "$session_name:2"
    tmux rename-window 'edit'
    tmux send-keys -t $session_name "vim ." C-m

  tmux select-window -t "$session_name:1"

fi

echo "status_bg = $status_bg"

if [ -z $2 ]
then
   echo "no second argument"
   echo "attempting to use .tmux-config.json"

   echo "inside if, status_bg = $status_bg"

   if [ -z ${status_bg+x} ];
   then
     echo "no status_bg set in config"
     $status_bg=colour244
   else
     echo "setting status-bg from config: $status_bg"
   fi

   if [ -z ${status_fg+x} ];
   then
     echo "no status_fg set in config; setting default"
     $status_fg=colour15
   else
     echo "setting status-fg from config: $status_fg"
   fi

  tmux set -a -t $session_name status-style bg=$status_bg,fg=$status_fg
else
  tmux set -a -t $session_name status-style bg=$2
fi

tmux a -t $session_name
